# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wgt_jaccard <- function(corpus, wgts, x, y, nthreads) {
    .Call(`_fedmatch_wgt_jaccard`, corpus, wgts, x, y, nthreads)
}

wgt_jaccard_single <- function(corpus, wgts, x, y, nthreads) {
    .Call(`_fedmatch_wgt_jaccard_single`, corpus, wgts, x, y, nthreads)
}

